$( document ).ready(function() {
    console.log( "ready!" );

    

    

    // function change () {
    // 	$(':button').click = change;
    // 	$('instructions').text('Now scroll to see your chord!');
    // };

     // $(":button").click(function(){
        // $("#instructions").text("Now scroll to see your chord!");
    // });

    //   $(window).scroll(function(){
    //     $("#notes").FadeOut()
    // })



             
    //     $(window).scroll(function(){                          
    //         if ($(this).scrollTop() < 1) {
    //             $('#notes').fadeIn(500);
    //         } else {
    //             $('#notes').fadeOut(500);
    //         }
    //     });
    // });

// key button state changes

 // $("#CM").click(function(){
        // $("#CM").css("background-color", "red");
    // });

$("#resetButton").click(function(){
        location.reload();

});


  // $("#noteCC").fadeIn(500);

 // var audio = $("#mysoundclip")[0];
 //      console.log(audio);
 //  $("CM").click(function() {
 //      audio.play();
 //  });


$("#CM").click(function(){
        // var audio = $("#mysoundclip") [0]
        // location.reload();
        // event.preventDefault();
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteD").hide();
        $("#noteA").hide();
        $("#noteB").hide();
        $("#noteD").hide();
        $("#noteE").hide();
        $("#noteF").hide();
        $("#Fsharp").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#F5')[0].pause();
        $('#B3')[0].pause();
        $('#D5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $("#seven").show();
        $("#noteCC").show();
        $('#C4')[0].play();
        $("#noteEE").show();
        $('#E4')[0].play();
        $("#noteG").show();
        $('#G4')[0].play();
        $("#noteC").show();
        $('#C5')[0].play();
        $("#GM").css("background-color", "#ff00e5");
        $("#CM").css("background-color", "white");
        $("#CM").css("color", "#ff00e5");
       
        //  location.reload();
        
     });

$("#GM").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteB").hide();
        $("#noteC").hide();
        $("#noteE").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#D5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#noteG").show();
        $('#G4')[0].play();
        $("#noteB").show();
        $('#B4')[0].play();
        $("#noteD").show();
        $('#D4')[0].play();
        $("#Fsharp").show();
        $("#CM").css("background-color", "#ff00e5");
        $("#GM").css("color", "#ff00e5");
        $("#GM").css("background-color", "white");

      });

$("#DM").click(function(){
		$(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteEE").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteC").hide();
        $("#noteE").hide();
        $("#noteF").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $('#D4')[0].play();
        $('#FsharpAudio')[0].play();
        $('#A4')[0].play();
        $('#D5')[0].play();
        $("#noteDD").show();
        $("#noteFF").show();
        $("#noteA").show();
        $("#noteD").show();
        $("#Fsharp").show();
        $("#Csharp").show();
        $("#DM").css("color", "#ff00e5");
        $("#DM").css("background-color", "white");


      });

$("#AM").click(function(){
        $('#C4')[0].pause();
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteFF").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $('#A4')[0].play();
        $("#noteA").show();
        $('#CsharpAudio')[0].play();
        $("#noteC").show();
        $('#E5')[0].play();
        $("#noteE").show();
        $("#Fsharp").show();
        $("#Csharp").show();
        $("#Gsharp").show();
        $("#AM").css("color", "#ff00e5");
        $("#AM").css("background-color", "white");

      });

$("#EM").click(function(){
        $('#C4')[0].pause();
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#noteEE").show();
        $('#E4')[0].play();
        $('#GsharpAudio')[0].play();
        $('#B4')[0].play();
        $('#E5')[0].play();
        $("#noteG").show();
        $("#noteB").show();
        $("#noteE").show();
        $("#Fsharp").show();
        $("#Csharp").show();
        $("#Gsharp").show();
        $("#Dsharp").show();
        $("#EM").css("color", "#ff00e5");
        $("#EM").css("background-color", "white");

      });

$("#BM").click(function(){
        $('#C4')[0].pause();
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Esharp").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteFF").hide();
        $("#noteG").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteE").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#noteB").show();
        $('#B4')[0].play();
        $("#noteD").show();
        $('#DsharpAudio2')[0].play();
        $("#noteF").show();
        $('#Fsharp5')[0].play()
        $("#Fsharp").show();
        $("#Csharp").show();
        $("#Gsharp").show();
        $("#Dsharp").show();
        $("#Asharp").show();
        $("#BM").css("color", "#ff00e5");
        $("#BM").css("background-color", "white");


      });

$("#FsharpMajor").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteD").hide();
        $("#noteE").hide();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#noteFF").show();
        $("#noteA").show();
        $("#noteC").show();
        $("#noteF").show();
        $("#Fsharp").show();
        $('#FsharpAudio')[0].play()
        $('#AsharpAudio')[0].play()
        $('#CsharpAudio')[0].play()
        $('#Fsharp5')[0].play()
        $("#Csharp").show();
        $("#Gsharp").show();
        $("#Dsharp").show();
        $("#Asharp").show();
        $("#Esharp").show();
        $("#FsharpMajor").css("color", "#ff00e5");
        $("#FsharpMajor").css("background-color", "white");


      });

$("#G♭M").click(function(){
        $('#C4')[0].pause();
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
		$("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteE").hide();
        $("#noteF").hide();
        $("#Fsharp").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#noteG").show();
        $('#FsharpAudio')[0].play();
        $('#AsharpAudio')[0].play();
        $('#CsharpAudio')[0].play();
        $("#noteB").show();
        $("#noteD").show();
        $("#Bflat").show();
        $("#Eflat").show();
        $("#Aflat").show();
        $("#Dflat").show();
        $("#Gflat").show();
        $("#Cflat").show();
        $("#G♭M").css("color", "#ff00e5");
        $("#G♭M").css("background-color", "white");

 });

$("#D♭M").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $("#Fsharp").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#noteEE").hide();
        $("#noteG").hide();
        $("#noteA").hide();
        $("#noteB").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteE").hide();
        $("#noteF").hide();
        $("#Cflat").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#noteDD").show();
        $('#Csharp4')[0].play();
        $("#noteFF").show();
        $('#F4')[0].play();
        $('#GsharpAudio')[0].play();
        $("#noteA").show();
        $("#noteD").show();
        $('#CsharpAudio')[0].play();
        $("#Bflat").show();
        $("#Eflat").show();
        $("#Aflat").show();
        $("#Dflat").show();
        $("#Gflat").show();
        $("#D♭M").css("color", "#ff00e5");
        $("#D♭M").css("background-color", "white");


      });

$("#A♭M").click(function(){
        $('#C4')[0].pause();
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#F5')[0].pause();
        $("#Cflat").hide();
        $("#Fsharp").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#Gflat").hide();
        $("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteFF").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#noteA").show();
        $('#GsharpAudio')[0].play();
        $("#noteC").show();
        $('#C5')[0].play();
        $("#noteE").show();
        $("#Bflat").show();
        $('#DsharpAudio2')[0].play();
        $("#Eflat").show();
        $("#Aflat").show();
        $("#Dflat").show();
        $("#A♭M").css("color", "#ff00e5");
        $("#A♭M").css("background-color", "white");
       
      });

$("#E♭M").click(function(){
		$('#C4')[0].pause();
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#F5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $("#Fsharp").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#noteEE").show();
        $('#DsharpAudio')[0].play();
        $("#noteG").show();
        $('#G4')[0].play();
        $("#noteB").show();
        $("#noteE").show();
        $("#Bflat").show();
        $("#Eflat").show();
        $('#AsharpAudio')[0].play();
        $('#DsharpAudio2')[0].play();
		$("#Aflat").show();
        $("#E♭M").css("color", "#ff00e5");
        $("#E♭M").css("background-color", "white");
       
      });

$("#B♭M").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#F5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $("#Fsharp").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteFF").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteE").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#noteB").show();
        $('#AsharpAudio')[0].play();
        $("#noteD").show();
        $('#D5')[0].play();
        $("#noteF").show();
        $('#F5')[0].play();
        $("#Bflat").show();
        $("#Eflat").show();
        $("#B♭M").css("color", "#ff00e5");
        $("#B♭M").css("background-color", "white");
       
      });

$("#FM").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#F5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $("#Fsharp").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteFF").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#Eflat").hide();
        $("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteD").hide();
        $("#noteE").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#noteFF").show();
        $('#F4')[0].play();
        $("#noteA").show();
        $('#A4')[0].play();
        $("#noteC").show();
        $('#C5')[0].play();
        $("#Bflat").show();
        $('#F5')[0].play();
        $("#noteF").show();
        $("#FM").css("color", "#ff00e5");
        $("#FM").css("background-color", "white");
       
      });

$("#Am").click(function(){
        $('#C4')[0].pause();
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteDD").hide();
        $("#noteEE").hide();
        $("#noteFF").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Fsharp").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Asharp").hide();
        $("#Esharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $('#A4')[0].play();
        $("#noteA").show();
        $('#C5')[0].play();
        $("#noteC").show();
        $('#E5')[0].play();
        $("#noteE").show();
        $("#Am").css("color", "#14ccbb");
        $("#Am").css("background-color", "white");

      });

$("#Em").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $("#noteEE").show();
        $('#E4')[0].play();
        $('#G4')[0].play();
        $('#B4')[0].play();
        $('#E5')[0].play();
        $("#noteG").show();
        $("#noteB").show();
        $("#noteE").show();
        $("#Fsharp").show();
        $("#Em").css("color", "#14ccbb");
        $("#Em").css("background-color", "white");

      });

$("#Bm").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $('#B4')[0].play();
        $('#D5')[0].play();
        $('#Fsharp5')[0].play();
        $("#noteB").show();
        $("#noteD").show();
        $("#noteF").show();
        $("#Fsharp").show();
        $("#Csharp").show();
        $("#Bm").css("color", "#14ccbb");
        $("#Bm").css("background-color", "white");

      });

$("#FsharpMinor").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $('#FsharpAudio')[0].play();
        $('#A4')[0].play();
        $('#CsharpAudio')[0].play();
        $('#Fsharp5')[0].play();
        $("#noteFF").show();
        $("#noteA").show();
        $("#noteC").show();
        $("#noteF").show();
        $("#Fsharp").show();
        $("#Csharp").show();
        $("#Gsharp").show();
        $("#FsharpMinor").css("color", "#14ccbb");
        $("#FsharpMinor").css("background-color", "white");

      });

$("#CsharpMinor").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $('#Csharp4')[0].play();
        $('#E4')[0].play();
        $('#GsharpAudio')[0].play();
        $('#CsharpAudio')[0].play();
        $("#seven").show();
        $("#noteCC").show();
        $("#noteA").show();
        $("#noteC").show();
        $("#noteF").show();
        $("#Fsharp").show();
        $("#Csharp").show();
        $("#Gsharp").show();
        $("#Dsharp").show();
        $("#CsharpMinor").css("color", "#14ccbb");
        $("#CsharpMinor").css("background-color", "white");

      });

$("#GsharpMinor").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $('#GsharpAudio')[0].play();
        $('#B4')[0].play();
        $('#DsharpAudio2')[0].play();
        $("#noteG").show();
        $("#noteB").show();
        $("#noteD").show();
        $("#Fsharp").show();
        $("#Csharp").show();
        $("#Gsharp").show();
        $("#Dsharp").show();
        $("#Asharp").show();
        $("#GsharpMinor").css("color", "#14ccbb");
        $("#GsharpMinor").css("background-color", "white");

      });

$("#DsharpMinor").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $('#DsharpAudio')[0].play();
        $('#FsharpAudio')[0].play();
        $('#AsharpAudio')[0].play();
        $('#DsharpAudio2')[0].play();
        $("#noteDD").show();
        $("#noteFF").show();
        $("#noteA").show();
        $("#noteD").show();
        $("#Fsharp").show();
        $("#Csharp").show();
        $("#Gsharp").show();
        $("#Dsharp").show();
        $("#Asharp").show();
        $("#Esharp").show();
        $("#DsharpMinor").css("color", "#14ccbb");
        $("#DsharpMinor").css("background-color", "white");
      });

$("#E♭m").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $("#Fsharp").hide();
        $('#DsharpAudio')[0].play();
        $('#FsharpAudio')[0].play();
        $('#AsharpAudio')[0].play();
        $('#DsharpAudio2')[0].play();
        $("#noteEE").show();
        $("#noteG").show();
        $("#noteB").show();
        $("#noteE").show();
        $("#Bflat").show();
        $("#Eflat").show();
        $("#Aflat").show();
        $("#Dflat").show();
        $("#Gflat").show();
        $("#Cflat").show();
        $("#E♭m").css("color", "#14ccbb");
        $("#E♭m").css("background-color", "white");

      });

$("#B♭m").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $("#Fsharp").hide();
        $('#AsharpAudio')[0].play();
        $('#CsharpAudio')[0].play();
        $('#F5')[0].play();
        $("#noteB").show();
        $("#noteD").show();
        $("#noteF").show();
        $("#Bflat").show();
        $("#Eflat").show();
        $("#Aflat").show();
        $("#Dflat").show();
        $("#Gflat").show();
        $("#B♭m").css("color", "#14ccbb");
        $("#B♭m").css("background-color", "white");

      });

$("#Fm").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $("#Fsharp").hide();
        $('#F4')[0].play();
        $('#GsharpAudio')[0].play();
        $('#C5')[0].play();
        $('#F5')[0].play();
		$("#noteFF").show();
        $("#noteA").show();
        $("#noteC").show();
        $("#noteF").show();
        $("#Bflat").show();
        $("#Eflat").show();
        $("#Aflat").show();
        $("#Dflat").show();
        $("#Fm").css("color", "#14ccbb");
        $("#Fm").css("background-color", "white");

      });

$("#Cm").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $("#Fsharp").hide();
        $('#C4')[0].play();
        $('#DsharpAudio')[0].play();
        $('#G4')[0].play();
        $('#C5')[0].play();
        $("#seven").show();
		$("#noteCC").show();
        $("#noteEE").show();
        $("#noteG").show();
        $("#noteC").show();
        $("#Bflat").show();
        $("#Eflat").show();
        $("#Aflat").show();
        $("#Cm").css("color", "#14ccbb");
        $("#Cm").css("background-color", "white");

      });

$("#Gm").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $("#Fsharp").hide();
        $('#G4')[0].play();
        $('#AsharpAudio')[0].play();
        $('#D5')[0].play();
        $("#noteG").show();
        $("#noteB").show();
        $("#noteD").show();
        $("#Bflat").show();
        $("#Eflat").show();
   		$("#Gm").css("color", "#14ccbb");
        $("#Gm").css("background-color", "white");
      });

$("#Dm").click(function(){
        $(".majorButton").css("background-color", "#ff00e5");
        $(".majorButton").css("color", "white");
        $(".minorButton").css("background-color", "#14ccbb");
        $(".minorButton").css("color", "white");
        $('#C4')[0].pause();
        $('#E4')[0].pause();
        $('#G4')[0].pause();
        $('#C5')[0].pause();
        $('#B3')[0].pause();
        $('#B4')[0].pause();
        $('#D4')[0].pause();
        $('#FsharpAudio')[0].pause();
        $('#A4')[0].pause();
        $('#E5')[0].pause();
        $('#CsharpAudio')[0].pause();
        $('#GsharpAudio')[0].pause();
        $('#DsharpAudio')[0].pause();
        $('#DsharpAudio2')[0].pause();
        $('#AsharpAudio')[0].pause();
        $('#D5')[0].pause();
        $('#Fsharp5')[0].pause();
        $('#Csharp4')[0].pause();
        $('#F4')[0].pause();
        $('#F5')[0].pause();
        $("#Bflat").hide();
        $("#Eflat").hide();
        $("#Aflat").hide();
        $("#Dflat").hide();
        $("#Gflat").hide();
        $("#Cflat").hide();
        $("#noteG").hide();
        $("#noteB").hide();
        $("#noteE").hide();
        $("#noteEE").hide();
        $("#noteDD").hide();
        $("#noteFF").hide();
        $("#noteA").hide();
        $("#noteC").hide();
        $("#noteD").hide();
        $("#noteF").hide();
        $("#Asharp").hide();
        $("#seven").hide();
        $("#noteCC").hide();
        $("#Csharp").hide();
        $("#Gsharp").hide();
        $("#Dsharp").hide();
        $("#Esharp").hide();
        $("#Fsharp").hide();
        $('#D4')[0].play();
        $('#F4')[0].play();
        $('#A4')[0].play();
        $('#D5')[0].play();
        $("#noteDD").show();
        $("#noteFF").show();
        $("#noteA").show();
        $("#noteD").show();
        $("#Bflat").show();
        $("#Dm").css("color", "#14ccbb");
        $("#Dm").css("background-color", "white");

      });










// $('#CM').click(function(){

// $(this).find('#noteA').toggle('fast');

// });

});



























